[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisord.log
logfile_maxbytes=10MB

[program:public-app]
user=public-user
command=gunicorn -w 1 -b 127.0.0.1:5000 --access-logfile /tmp/app.log --access-logformat "%%(t)s - %%(r)s" app:app
directory=/app/public-app
environment=FLAG="upCTF{...}"
autostart=true
autorestart=true
stdout_logfile=/var/log/public-app.log
stderr_logfile=/var/log/public-app-err.log

[program:admin-app]
user=admin-user
command=gunicorn -w 2 -b 127.0.0.1:5001 app:app
directory=/app/admin-app
environment=UPLOAD_BASE="/app/admin-app/uploads",CERT_STORE_PATH="/app/certs"
autostart=true
autorestart=true
stdout_logfile=/var/log/admin-app.log
stderr_logfile=/var/log/admin-app-err.log

[program:tls-proxy]
user=proxy-user
command=/app/proxy/tls_proxy
directory=/app/proxy
environment=PUBLIC_APP_HOST="127.0.0.1",PUBLIC_APP_PORT="5000",ADMIN_APP_HOST="127.0.0.1",ADMIN_APP_PORT="5001",CERT_STORE_PATH="/app/certs"
autostart=true
autorestart=true
stdout_logfile=/var/log/proxy.log
stderr_logfile=/var/log/proxy-err.log
